### ISSUE TITLE
Route drag and drop inserts stop in unexpected order

### ISSUE THREAD

**Issue by steventebrinke** [GIScience/ors-map-client#103]
When dragging and dropping a route, a stop is inserted in het segment nearest to the drop point, but I would expect it to be inserted in the segment being dragged. This is quite annoying when planning round trips.
To reproduce: create any route from 1 to 2 to 3. Now drag the segment between 2 and 3 to a point closer to the segment between 1 and 2. The inserted stop is added as stop 2, but I had expected this to be stop 3.

**Comment by amoncaldas** [comment]
Hey @steventebrinke 
Thanks for your comment.

I tried to reproduce your use case and for me it seems to have the expected behavior. See images attached.

<img width="1437" alt="route-1-2-3" src="https://user-images.githubusercontent.com/13475791/110622669-0b560480-819c-11eb-83f0-97b6bf2740fb.png">
<img width="1433" alt="drag-segment-between-2-and-3" src="https://user-images.githubusercontent.com/13475791/110622671-0db85e80-819c-11eb-8984-20a175e7bb33.png">
<img width="1435" alt="result" src="https://user-images.githubusercontent.com/13475791/110622679-0ee98b80-819c-11eb-90ee-d0a5155d3875.png">

**Comment by koebi** [comment]
Hey,
I also cannot reproduce the behaviour mentioned by @steventebrinke but I can reproduce something that strikes me as equally odd:
When creating a route 1 -> 2 -> 3 and dragging a point on the route between 1 and 2, it adds the point I drag to as a new point 3 instead of the new point 2 and shifting 2 and 3 by one.
The following three screenshots illustrate the point:
![Screenshot_2021-03-16 ORS Maps](https://user-images.githubusercontent.com/4692974/111297404-dfc89380-864d-11eb-9b87-8203cc0d5e31.png)
![Screenshot_2021-03-16 ORS Maps(1)](https://user-images.githubusercontent.com/4692974/111297407-e0612a00-864d-11eb-8094-a5d7b4399555.png)
![Screenshot_2021-03-16 ORS Maps(2)](https://user-images.githubusercontent.com/4692974/111297409-e0612a00-864d-11eb-8ee5-5c171345621e.png)

**Comment by amoncaldas** [comment]
Hey @koebi 
Thanks for reporting this. I could reproduce it and already found the bug for this specific case.

**Comment by amoncaldas** [comment]
Fixed

**Comment by TheGreatRefrigerator** [comment]
This is still an issue on maps.openrouteservice.org

https://user-images.githubusercontent.com/23240110/114539002-48f2f500-9c54-11eb-85bf-8a5db06708f8.mov

**Comment by amoncaldas** [comment]
Hey @TheGreatRefrigerator 
Currently when a point is dragged, a stop is added right after the closest existing stop. You are arguing that the stop should be inserted between the existing stops *from where the points was dragged from*? Is that right? If that is the case, I think we might get complaints in the other way around. So maybe we should have an option for this?

**Comment by koebi** [comment]
Hey,

yes, that's also how I would expect dragging to behave.
In my eyes, when dragging a part of the route, the user wants to change this part of the route as it currently exists to instead go via the point that is being dragged to.

**Comment by koebi** [comment]
I have been looking at the behaviour of komoot, gmaps, osrm and brouter when dragging points from a route.
All of them will add a new point in the segment that is being dragged, leaving the start- and endpoint of this segment untouched and changing that segment to include the new point.,

I think this gives a strong indication that this is the expected behaviour of dragging a point from a route.

**Comment by amoncaldas** [comment]
Now the route optimization after a stop is added only happens if this option is explicitly defined in app settings. Otherwise the app will add the stop considering where the user dragged the point from.
Closed via https://github.com/GIScience/ors-map-client/commit/1d562c6f294c1995cb93ec3f576fea5d4f1b660a
